baseURL = "https://thesayfulla.github.io/"
title = "Sayfulla's blog"
languageCode = "en-us"
theme = "paper"
paginate = 10

[params]
  titleCutting = true
  color = 'light'
  github = 'thesayfulla'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10


[params.giscus]
  repo = 'thesayfulla/thesayfulla.github.io'                 # see https://giscus.app for more details
  repoId = 'R_kgDOKfhCgg'
  category = 'Q&A'
  categoryId = 'DIC_kwDOKfhCgs4Cnrk1'
  mapping = 'pathname'
  theme = 'light'
  lang = 'en'